site_name: Python Cowsay Tutorial

theme:
  name: material  
  logo: images/krowo_ikonka.png
  favicon: images/krowo_ikonka.png
  extra_css:
    - css/float-cow.css
  extra_javascript:
    - js/float-cow.js
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pl
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Tryb ciemny
      primary: deep purple  
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Tryb jasny
      primary: indigo 
      accent: blue

copyright: |
  &copy; 2025 <br><a href="https://github.com/m4rcelrad"  target="_blank" rel="noopener">Marcel Radwa≈Ñski</a><br>
  <a href="https://github.com/Z1AJA"  target="_blank" rel="noopener">Szymon Ziajski</a>
